title: Richmond Chris-Koka
logo: "/images/selikem11.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Engineer| Python Programmer | Researcher
  <br><br>
  Proactive problem solver with excellent communication abilities and a Bachelor's degree in Computer Science. Highly analytical individual with strong apt for learning and collaborative skills. Looking to apply extensive data science experience in a fast-paced and dynamic firm to create data collection models that generate insight
  <br><br>
  <a href="https://www.linkedin.com/in/rchriskoka/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
