---
title: My Data Eng Portfolio
author: Elvis Lartey
email: larteyelvis@outlook.com
description: A goal-oriented Data Engineer with strong commitment to collaboration
  and solutions oriented problem-solving. I am a self motivated individual who is
  committed to high standards of development, user experience and usability and successful
  at maintaining customer satisfaction through effective customer support and collaboration.
baseurl: "/ubuild-jekyll"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
