---
title: Data Science & Engineering Portfolio
author: Richmond Chris-Koka
email: rchriskoka@gmail.com
description: Result-oriented data engineer with with great communication skills and a background in Pharmacy. I am a highly analytical person with strong apt for learning and collaborative skills, detail oriented and possess the ability to adapt quickly in the fast-paced tech sapce. Looking to apply my knowledge in data engineering extensively to solve problems pertaining to data infrastructure.
baseurl: "/ubuild-jekyll"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
